### ISSUE TITLE
remove deprecated --path flag from Readme

### ISSUE THREAD

**Issue by Am3ra** [rust-embedded/rust-raspberrypi-OS-tutorials#60]
When following the install scripts in the main README, i get the following warning:

bundle install --path .vendor/bundle

[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path '.vendor/bundle'`, and stop using this flag

**Comment by andre-richter** [comment]
I had previously tried the suggested alternative command, but it did not work for me. Hence I haven't addressed this yet. 

Did you give it a try?

**Comment by Am3ra** [comment]
No, but thanks for the suggestion, didn't even consider it! I will! (Btw, love this repo, still trying to figure out how to use it well)

**Comment by Am3ra** [comment]
Completely uninstalled the gem, and reinstalled it without the `--path` flag, installed correctly and then ran the `bundle config set path '.vendor/bundle'` command. No problems so far running.

**Comment by andre-richter** [comment]
> Completely uninstalled the gem, and reinstalled it without the `--path` flag, installed correctly and then ran the `bundle config set path '.vendor/bundle'` command. No problems so far running.

I think that only worked because it installed the Gems globally :thinking: 

The goal is that the installation of the gems itself ends up in the vendor folder, so installation would need to happen after `bundle config set path '.vendor/bundle'` but it then never worked for me like intended.

I'll keep the bug open until I find some motivation to revisit this :smile:
